mysite/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from solid_i18n.urls import solid_i18n_patterns
from django.views.static import serve

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^auth/', include('users.urls')),
    url(r'^', include('calculation.urls')),
]

urlpatterns += solid_i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from .views import login_view, logout_view

urlpatterns = [
    url(r'^login/$', login_view, name='login_view'),
    url(r'^logout/$', logout_view, name='logout_view'),
]

calculation/forms.py
from django import forms
from database_item.models import Item, ItemManufacturer, ItemCategory


class CalcForm (forms.Form):
    comment = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'placeholder': u'Назначение', 'class': 'form-control'}),
                              )


class CalcNmb (forms.Form):
    calc_nmb = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control', 'pattern': '^[ 1-9]+$'}),
                                  required=True, initial=1)


class CalcDriveForm (forms.Form):

    CHOISES_VOLTAGE = (
        ('380', '380 ~'),
        ('690', '690 ~'),
    )

    CHOISES_POWER = (
        (None, '-----'),
        ('0.75', '0,75'), ('1.5', '1,5'), ('2.2', '2,2'), ('3', '3'), ('4', '4'), ('5.5', '5,5'), ('7.5', '7,5'),
        ('11', '11'), ('15', '15'), ('18.5', '18,5'), ('22', '22'), ('30', '30'), ('37', '37'),
        ('45', '45'), ('55', '55'), ('75', '75'), ('90', '90'), ('110', '110'), ('132', '132'),
        ('160', '160'), ('200', '200'), ('220', '220'), ('250', '250'), ('280', '280'), ('315', '315'),
        ('355', '355'), ('400', '400'), ('500', '500')
    )

    TYPE_COMMUTATION = (
        ('Streight', u'Прямой пуск'),
        ('SoftStart', u'Устройство плавного пуска'),
        ('FreqConvert', u'Частотный преобразователь'),
    )

    TYPE_TERMINALS = (
        (None, '-----'),
        ('Screw', u'Винтовые'),
        ('Spring', u'Пружинные'),
        ('PushIn', u'Push-In'),
    )

    calc_drive = forms.IntegerField(widget=forms.HiddenInput(), initial='1')

    calc_drive_voltage=forms.ChoiceField(choices=CHOISES_VOLTAGE, widget=forms.Select(attrs={'class': 'form-control'}),)

    calc_drive_power = forms.ChoiceField(choices=CHOISES_POWER, widget=forms.Select(attrs={'class': 'form-control'}),)

    calc_drive_type = forms.ChoiceField(choices=TYPE_COMMUTATION, widget=forms.Select(attrs={'class': 'form-control'}),)

    # Получаем всех производителей из родительской категории
    calc_drive_manufacturer = forms.ModelChoiceField(queryset=ItemManufacturer.objects\
                                                     .filter(item__category__in=ItemCategory.objects.get(name=u'Силовая коммутация')\
                                                             .get_descendants(include_self=True))\
                                                     .values_list('name', flat=True)\
                                                     .distinct(),
                                          required=False,
                                          widget=forms.Select(attrs={'class': 'form-control'})
                                          )

    calc_drive_series = forms.ModelChoiceField(queryset=Item.objects\
                                               .filter(category__in=ItemCategory.objects.get(name=u'Силовая коммутация')
                                                       .get_descendants(include_self=True))
                                               .values_list('series', flat=True).distinct(),
                                         required=False,
                                         widget=forms.Select(attrs={'class': 'form-control'})
                                         )

    calc_drive_reverse = forms.BooleanField(widget=forms.CheckboxInput(), label=u'Реверс', required=False)
    calc_drive_bypass = forms.BooleanField(widget=forms.CheckboxInput(), label='Bypass', required=False)

    calc_drive_discret_input = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control',
                                                                                  'pattern': '^[ 0-9]+$'}),
                                                  label=u'Дискретные входы',
                                                  required=False)
    calc_drive_discret_output = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control',
                                                                                  'pattern': '^[ 0-9]+$'}),
                                                  label=u'Дискретные выходы',
                                                  required=False)
    calc_drive_analog_input = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control',
                                                                                  'pattern': '^[ 0-9]+$'}),
                                                  label=u'Аналоговые входы',
                                                  required=False)
    calc_drive_analog_output = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control',
                                                                                  'pattern': '^[ 0-9]+$'}),
                                                  label=u'Аналоговые выходы',
                                                  required=False)
    calc_drive_profinet = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control',
                                                                                  'pattern': '^[ 0-9]+$'}),
                                                  label=u'ProfiNet',
                                                  required=False)
    calc_drive_profibus = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control',
                                                                                  'pattern': '^[ 0-9]+$'}),
                                                  label=u'ProfiBus',
                                                  required=False)
    calc_drive_rs485 = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control',
                                                                                  'pattern': '^[ 0-9]+$'}),
                                             label=u'RS485',
                                             required=False)

    calc_drive_manufacturer_terminals = forms.ModelChoiceField(queryset=ItemManufacturer.objects\
                                                     .filter(item__category__in=ItemCategory.objects.get(name=u'Клеммы')\
                                                             .get_descendants(include_self=True))\
                                                     .values_list('name', flat=True)\
                                                     .distinct(),
                                            required=False,
                                            widget=forms.Select(attrs={'class': 'form-control'})
                                            )
    calc_drive_type_terminals = forms.ChoiceField(choices=TYPE_TERMINALS,
                                                  widget=forms.Select(attrs={'class': 'form-control'}),
                                                  required=False,
                                                  )

class CalcControlForm (forms.Form):

    CHOISES_VOLTAGE = (
        ('24', '24 ⎓'),
        ('220', '220 ~'),
    )

    TYPE_CONTROL = (
        (None, '-----'),
        ('PLC', u'ПЛК'),
        ('ProgrammableRelay', u'Программируемое реле'),
        ('Relay', u'Релейная схема'),
    )

    TYPE_TERMINALS = (
        (None, '-----'),
        ('Screw', u'Винтовые'),
        ('Spring', u'Пружинные'),
        ('PushIn', u'Push-In'),
    )

    CHOISES_RESERVE = (
        ('1', '0 %'), ('1.1', '10 %'), ('1.2', '20 %'), ('1.3', '30 %'), ('1.4', '40 %'), ('1.5', '50 %'),
        ('1.6', '60 %'), ('1.7', '70 %'), ('1.8', '80 %'), ('1.9', '90 %'), ('2', '100 %')
    )

    calc_control = forms.IntegerField(widget=forms.HiddenInput(), initial='1')

    calc_control_voltage = forms.ChoiceField(choices=CHOISES_VOLTAGE,
                                           widget=forms.Select(attrs={'class': 'form-control'}), )

    calc_control_type = forms.ChoiceField(choices=TYPE_CONTROL,
                                        widget=forms.Select(attrs={'class': 'form-control'}), )

    calc_control_discret_input = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control',
                                                                                  'pattern': '^[ 0-9]+$'}),
                                                  label=u'Дискретные входы',
                                                  required=True)
    calc_control_discret_output = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control',
                                                                                   'pattern': '^[ 0-9]+$'}),
                                                   label=u'Дискретные выходы',
                                                   required=True)

    # Получаем всех производителей из родительской категории
    calc_control_manufacturer = forms.ModelChoiceField(queryset=ItemManufacturer.objects\
                                                     .filter(item__category__in=ItemCategory.objects.get(name=u'Управление')\
                                                     .get_descendants(include_self=True))\
                                                     .values_list('name', flat=True)\
                                                     .distinct(),
                                                     required=False,
                                                     widget=forms.Select(attrs={'class': 'form-control'})
                                                     )

    calc_control_series = forms.ModelChoiceField(queryset=Item.objects\
                                               .filter(category__in=ItemCategory.objects.get(name=u'Управление')
                                               .get_descendants(include_self=True))\
                                               .values_list('series', flat=True).distinct(),
                                               required=False,
                                               widget=forms.Select(attrs={'class': 'form-control'})
                                               )

mysite/templates/plugins/calc/calc_control.html
{% load cms_tags staticfiles sekizai_tags %}
<div class="calc_control {{ instance.tag_class }}" id="calc_control-{{ instance.id }}" style="{{ instance.tag_style }}">
    {{ calc_control.calc_control }}
    <div class="form-group input-group">
        <div class="input-group-addon">{{ instance.voltage }}</div>
        {{ calc_control.calc_control_voltage }}
        <div class="input-group-addon">{{ instance.voltage_unit }}</div>
    </div>
    <div class="form-group input-group">
        <div class="input-group-addon">{{ instance.type }}</div>
        {{ calc_control.calc_control_type }}
    </div>
    {% if instance.show_input_output %}
        <div class="form-group input-group" id="div_{{ calc_control.calc_control_discret_input.id_for_label }}">
            <div class="input-group-addon">{{ instance.discret_input }}</div>
            {{ calc_control.calc_control_discret_input }}
        </div>
        <div class="form-group input-group" id="div_{{ calc_control.calc_control_discret_output.id_for_label }}">
            <div class="input-group-addon">{{ instance.discret_output }}</div>
            {{ calc_control.calc_control_discret_output }}
        </div>
    {% endif %}
    {% for plugin in instance.child_plugin_instances %}
        {% render_plugin plugin %}
    {% endfor %}
    <a id="calc_control_more_button-{{ instance.id }}" class="form-control text-center" role="button" data-toggle="collapse" href="#collapseAdding_CalcControlAddFields-{{ instance.id }}" aria-expanded="false" aria-controls="collapseAdding_CalcControlAddFields-{{ instance.id }}">
      {{ instance.more }}
    </a>
    <div class="collapse" id="collapseAdding_CalcControlAddFields-{{ instance.id }}">
        <hr>
        <div class="form-group input-group">
            <div class="input-group-addon">{{ instance.manufacture_item }}</div>
            {{ calc_control.calc_control_manufacturer }}
        </div>
        <div class="form-group input-group">
            <div class="input-group-addon">{{ instance.series_item }}</div>
            {{ calc_control.calc_control_series }}
        </div>
        <div class="form-group input-group calc_plc calc_programmable_relay">
            <div class="input-group-addon">{{ instance.cpu_item }}</div>
            {{ calc_control.calc_control_cpu }}
        </div>
        <hr>
        <div class="form-group" id="calc_control_attribute">
            {% if instance.show_input_output %}
                <div class="input-group calc_relay" id="div_{{ calc_control.calc_control_time_delay.id_for_label }}">
                    <div class="input-group-addon">{{ calc_control.calc_control_time_delay.label }}</div>
                    {{ calc_control.calc_control_time_delay }}
                </div>
                <div class="input-group calc_plc" id="div_{{ calc_control.calc_control_fast_discret_input.id_for_label }}">
                    <div class="input-group-addon">{{ calc_control.calc_control_fast_discret_input.label }}</div>
                    {{ calc_control.calc_control_fast_discret_input }}
                </div>
                <div class="input-group calc_plc" id="div_{{ calc_control.calc_control_fast_discret_output.id_for_label }}">
                    <div class="input-group-addon">{{ calc_control.calc_control_fast_discret_output.label }}</div>
                    {{ calc_control.calc_control_fast_discret_output }}
                </div>
                <div class="input-group calc_plc calc_programmable_relay" id="div_{{ calc_control.calc_control_analog_0_10V_input.id_for_label }}">
                    <div class="input-group-addon">{{ calc_control.calc_control_analog_0_10V_input.label }}</div>
                    {{ calc_control.calc_control_analog_0_10V_input }}
                </div>
                <div class="input-group calc_plc calc_programmable_relay" id="div_{{ calc_control.calc_control_analog_0_10V_output.id_for_label }}">
                    <div class="input-group-addon">{{ calc_control.calc_control_analog_0_10V_output.label }}</div>
                    {{ calc_control.calc_control_analog_0_10V_output }}
                </div>
                <div class="input-group calc_plc calc_programmable_relay" id="div_{{ calc_control.calc_control_analog_0_20mA_input.id_for_label }}">
                    <div class="input-group-addon">{{ calc_control.calc_control_analog_0_20mA_input.label }}</div>
                    {{ calc_control.calc_control_analog_0_20mA_input }}
                </div>
                <div class="input-group calc_plc calc_programmable_relay" id="div_{{ calc_control.calc_control_analog_0_20mA_output.id_for_label }}">
                    <div class="input-group-addon">{{ calc_control.calc_control_analog_0_20mA_output.label }}</div>
                    {{ calc_control.calc_control_analog_0_20mA_output }}
                </div>
                <div class="input-group calc_plc calc_programmable_relay" id="div_{{ calc_control.calc_control_analog_rtd_input.id_for_label }}">
                    <div class="input-group-addon">{{ calc_control.calc_control_analog_rtd_input.label }}</div>
                    {{ calc_control.calc_control_analog_rtd_input }}
                </div>
            {% endif %}
            <div class="input-group calc_plc" id="div_{{ calc_control.calc_control_profinet.id_for_label }}">
                <div class="input-group-addon">{{ calc_control.calc_control_profinet.label }}</div>
                {{ calc_control.calc_control_profinet }}
            </div>
            <div class="input-group calc_plc" id="div_{{ calc_control.calc_control_profibus.id_for_label }}">
                <div class="input-group-addon">{{ calc_control.calc_control_profibus.label }}</div>
                {{ calc_control.calc_control_profibus }}
            </div>
            <div class="input-group calc_plc calc_programmable_relay" id="div_{{ calc_control.calc_control_modbus_tcp.id_for_label }}">
                <div class="input-group-addon">{{ calc_control.calc_control_modbus_tcp.label }}</div>
                {{ calc_control.calc_control_modbus_tcp }}
            </div>
            <div class="input-group calc_plc calc_programmable_relay" id="div_{{ calc_control.calc_control_modbus_rtu.id_for_label }}">
                <div class="input-group-addon">{{ calc_control.calc_control_modbus_rtu.label }}</div>
                {{ calc_control.calc_control_modbus_rtu }}
            </div>
        </div>
        <hr>
        <div class="form-group input-group">
            <div class="input-group-addon">{{ instance.manufacture_relays }}</div>
            {{ calc_control.calc_control_manufacturer_relays }}
        </div>
        <div class="form-group input-group">
            <div class="input-group-addon">{{ instance.series_relays }}</div>
            {{ calc_control.calc_control_series_relays }}
        </div>
        <hr>
        <div class="form-group input-group">
            <div class="input-group-addon">{{ instance.manufacture_terminal }}</div>
            {{ calc_control.calc_control_manufacturer_terminals }}
        </div>
        <div class="form-group input-group">
            <div class="input-group-addon">{{ instance.type_terminal }}</div>
            {{ calc_control.calc_control_type_terminals }}
        </div>
        {% if instance.show_reserve %}
        <div class="form-group input-group">
            <div class="input-group-addon">{{ instance.reserve }}</div>
            {{ calc_control.calc_control_reserve }}
        </div>
        {% endif %}
    </div>
    <hr>
</div>

{% addtoblock "js" %}
<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function(){
        //Изменение отображения атрибутов при изменении выпадающего списка выбора типа пуска
        $('#calc_control-{{ instance.id }} #id_calc_control_type, #calc_control-{{ instance.id }} #calc_control_more_button-{{ instance.id }}').on("click",function() {
               var val = $('#calc_control-{{ instance.id }} #id_calc_control_type').val();
               if (val == 'PLC' ) {
                   $('#calc_control-{{ instance.id }} .calc_programmable_relay').hide();
                   $('#calc_control-{{ instance.id }} .calc_relay').hide();
                   $('#calc_control-{{ instance.id }} .calc_plc').show();
               }
               if (val == 'ProgrammableRelay') {
                   $('#calc_control-{{ instance.id }} .calc_plc').hide();
                   $('#calc_control-{{ instance.id }} .calc_relay').hide();
                   $('#calc_control-{{ instance.id }} .calc_programmable_relay').show();
               }
               if (val == 'Relay') {
                   $('#calc_control-{{ instance.id }} .calc_plc').hide();
                   $('#calc_control-{{ instance.id }} .calc_programmable_relay').hide();
                   $('#calc_control-{{ instance.id }} .calc_relay').show();
               }
               if (val == ''){
                   $('#calc_control-{{ instance.id }} .calc_plc').hide();
                   $('#calc_control-{{ instance.id }} .calc_relay').hide();
                   $('#calc_control-{{ instance.id }} .calc_programmable_relay').hide();

               }
        });
     });


    document.addEventListener("DOMContentLoaded", function(){

        CheckCalcControlFieldInCalculation('#calc_control-{{ instance.id }}');

        $(document).off('change','#calc_control-{{ instance.id }}').on('change','#calc_control-{{ instance.id }}', function() {
            CheckCalcControlFieldInCalculation('#calc_control-{{ instance.id }}');
            });

    });
</script>
{% endaddtoblock %}

mysite/templates/plugins/calc/calc_drive.html
{% load cms_tags staticfiles sekizai_tags %}
<div class="calc_drive {{ instance.tag_class }}" id="calc_drive-{{ instance.id }}" style="{{ instance.tag_style }}">
    {{ commute_drive.calc_drive }}
    <div class="form-group input-group">
        <div class="input-group-addon">{{ instance.voltage }}</div>
        {{ commute_drive.calc_drive_voltage }}
        <div class="input-group-addon">{{ instance.voltage_unit }}</div>
    </div>
    <div class="form-group input-group">
        <div class="input-group-addon">{{ instance.power }}</div>
        {{ commute_drive.calc_drive_power }}
        <div class="input-group-addon">{{ instance.power_unit }}</div>
    </div>
    <div class="form-group input-group">
        <div class="input-group-addon">{{ instance.type }}</div>
        {{ commute_drive.calc_drive_type }}
    </div>
    {% for plugin in instance.child_plugin_instances %}
        {% render_plugin plugin %}
    {% endfor %}
    <a id="calc_drive_more_button-{{ instance.id }}" class="form-control text-center" role="button" data-toggle="collapse" href="#collapseAdding_CalcDriveAddFields-{{ instance.id }}" aria-expanded="false" aria-controls="collapseAdding_CalcDriveAddFields-{{ instance.id }}">
      {{ instance.more }}
    </a>
    <div class="collapse" id="collapseAdding_CalcDriveAddFields-{{ instance.id }}">
        <hr>
        <div class="form-group input-group">
            <div class="input-group-addon">{{ instance.manufacture_item }}</div>
            {{ commute_drive.calc_drive_manufacturer }}
        </div>
        <div class="form-group input-group">
            <div class="input-group-addon">{{ instance.series_item }}</div>
            {{ commute_drive.calc_drive_series }}
        </div>
        <hr>
        <div class="form-group" id="commute_drive_attribute">
            <div class="checkbox calc_streight calc_softstart" id="div_{{ commute_drive.calc_drive_reverse.id_for_label }}">
                <label>
                {{ commute_drive.calc_drive_reverse }}{{ commute_drive.calc_drive_reverse.label }}
                </label>
            </div>
            <div class="checkbox calc_softstart calc_freqconvert" id="div_{{ commute_drive.calc_drive_bypass.id_for_label }}">
                <label>
                {{ commute_drive.calc_drive_bypass }}{{ commute_drive.calc_drive_bypass.label }}
                </label>
            </div>
            {% if instance.show_input_output %}
                <div class="input-group calc_softstart calc_freqconvert" id="div_{{ commute_drive.calc_drive_discret_input.id_for_label }}">
                    <div class="input-group-addon">{{ commute_drive.calc_drive_discret_input.label }}</div>
                    {{ commute_drive.calc_drive_discret_input }}
                </div>
                <div class="input-group calc_softstart calc_freqconvert" id="div_{{ commute_drive.calc_drive_discret_output.id_for_label }}">
                    <div class="input-group-addon">{{ commute_drive.calc_drive_discret_output.label }}</div>
                    {{ commute_drive.calc_drive_discret_output }}
                </div>
                <div class="input-group calc_freqconvert" id="div_{{ commute_drive.calc_drive_analog_input.id_for_label }}">
                    <div class="input-group-addon">{{ commute_drive.calc_drive_analog_input.label }}</div>
                    {{ commute_drive.calc_drive_analog_input }}
                </div>
                <div class="input-group calc_freqconvert" id="div_{{ commute_drive.calc_drive_analog_output.id_for_label }}">
                    <div class="input-group-addon">{{ commute_drive.calc_drive_analog_output.label }}</div>
                    {{ commute_drive.calc_drive_analog_output }}
                </div>
            {% endif %}
            <div class="input-group calc_freqconvert" id="div_{{ commute_drive.calc_drive_profinet.id_for_label }}">
                <div class="input-group-addon">{{ commute_drive.calc_drive_profinet.label }}</div>
                {{ commute_drive.calc_drive_profinet }}
            </div>
            <div class="input-group calc_softstart calc_freqconvert" id="div_{{ commute_drive.calc_drive_profibus.id_for_label }}">
                <div class="input-group-addon">{{ commute_drive.calc_drive_profibus.label }}</div>
                {{ commute_drive.calc_drive_profibus }}
            </div>
            <div class="input-group calc_freqconvert" id="div_{{ commute_drive.calc_drive_rs485.id_for_label }}">
                <div class="input-group-addon">{{ commute_drive.calc_drive_rs485.label }}</div>
                {{ commute_drive.calc_drive_rs485 }}
            </div>
        </div>
        <hr>
        <div class="form-group input-group">
            <div class="input-group-addon">{{ instance.manufacture_terminal }}</div>
            {{ commute_drive.calc_drive_manufacturer_terminals }}
        </div>
        <div class="form-group input-group">
            <div class="input-group-addon">{{ instance.type_terminal }}</div>
            {{ commute_drive.calc_drive_type_terminals }}
        </div>
    </div>
    <hr>
</div>

{% addtoblock "js" %}<script type="text/javascript" src="{{ STATIC_URL }}jquery/jquery-2.2.4.js"></script>{% endaddtoblock %}
{% addtoblock "js" %}
<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function(){
        //Изменение отображения атрибутов при изменении выпадающего списка выбора типа пуска
        $('#calc_drive-{{ instance.id }} #id_calc_drive_type, #calc_drive-{{ instance.id }} #calc_drive_more_button-{{ instance.id }}').on("click",function() {
               var val = $('#calc_drive-{{ instance.id }} #id_calc_drive_type').val();
               if (val == 'Streight' ) {
                   $('#calc_drive-{{ instance.id }} .calc_softstart').hide();
                   $('#calc_drive-{{ instance.id }} .calc_freqconvert').hide();
                   $('#calc_drive-{{ instance.id }} .calc_streight').show();
               }
               if (val == 'SoftStart') {
                   $('#calc_drive-{{ instance.id }} .calc_streight').hide();
                   $('#calc_drive-{{ instance.id }} .calc_freqconvert').hide();
                   $('#calc_drive-{{ instance.id }} .calc_softstart').show();
               }
               if (val == 'FreqConvert') {
                   $('#calc_drive-{{ instance.id }} .calc_streight').hide();
                   $('#calc_drive-{{ instance.id }} .calc_softstart').hide();
                   $('#calc_drive-{{ instance.id }} .calc_freqconvert').show();
               }
               if (val == ''){
                   $('#calc_drive-{{ instance.id }} .calc_streight').hide();
                   $('#calc_drive-{{ instance.id }} .calc_softstart').hide();
                   $('#calc_drive-{{ instance.id }} .calc_freqconvert').hide();
               }
        });
     });


document.addEventListener("DOMContentLoaded", function(){
    CheckCalcDriveFieldInCalculation(id='#calc_drive-{{ instance.id }}');

    $(document).off('change','#calc_drive-{{ instance.id }}').on('change','#calc_drive-{{ instance.id }}', function() {
        CheckCalcDriveFieldInCalculation(id='#calc_drive-{{ instance.id }}');
    });
});
</script>
{% endaddtoblock %}

mysite/templates/plugins/calc/calc_form.html
{% load cms_tags sekizai_tags %}
<form action="" method="post" class="calc_form {{ instance.tag_class }}" id="calc_form-{{ instance.id }}" style="{{ instance.tag_style }}">{% csrf_token %}
    {% if messages %}
        <div class="alert alert-warning alert-message alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <input class="hidden" type="text" name='pre_comment' value='{{ instance.comment }}'>
    <div class="form-group input-group">
        <div class="input-group-addon">{{ instance.comment }}</div>
        {{ form.comment }}
    </div>
    <hr>
    <div class="plugin_parent">
    {% for plugin in instance.child_plugin_instances %}
        {% render_plugin plugin %}
    {% endfor %}
    </div>
</form>

{# Скрипт затухания сообщений об ошибках #}
{% addtoblock "js" %}
<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function(){
        $('#calc_form-{{ instance.id }}').submit(function(e) {
            e.preventDefault();
            e.stopImmediatePropagation();
            UpdateHtmlFromAjax($(this), '#calc_form-{{ instance.id }}', '#calc_submit_button', '.alert-message');
            return false;
        });
    });
</script>
{% endaddtoblock %}

mysite/templates/plugins/calc/calc_nmb.html
{% load cms_tags sekizai_tags %}
<div class="form-group input-group {{ instance.tag_class }}" style="{{ instance.tag_style }}">
    <div class="input-group-addon">{{ instance.name }}</div>
    {{ form_calc_nmb.calc_nmb }}
</div>

mysite/templates/plugins/calc/calc_submit.html
{% load cms_tags %}
<div class="{{ instance.tag_class }}" style="{{ instance.tag_style }}">
    <button id="calc_submit_button" type="submit" class="{{ instance.button_class }}" style="{{ instance.button_style }}">{{ instance.name }}</button>
</div>